EducationBranch
TimonHC/SmartiansJS pull request #1
Opened 2020-03-23 09:50 UTC by TimonHC

completed tasks

2020-03-23 15:54 UTC, smartianin requested changes
В целом хорошо, единственное что:
- исправь замечания
- избавься от вложенной папки SmartiansJS
- в WebStorm обязательно проверяй, чтобы твой код работал. (правой кнопкой по файлу, main.js run)
–  в конце я хочу видеть вывод в консоль надпись, "Я закончил Раздел 1", зеленым цветом.

2020-03-23 15:54 UTC, smartianin commented on SmartiansJS/main.js
> +console.log(output = undefined, typeof(undefined));
Зачем ты присваиваешь значения в переменную, которую даже не определил?

2020-03-23 15:54 UTC, smartianin commented on SmartiansJS/main.js
> +console.log(Math.PI * 100);
Молодец))

2020-03-23 15:54 UTC, smartianin commented on SmartiansJS/main.js
> +console.log('     I love study JS on Smartians platform    '.trim());
Молодец!

2020-03-23 15:54 UTC, smartianin commented on SmartiansJS/main.js
> +console.log(Math.floor(Math.random() * (200 + 1)));
Тут слегка переусердствовал. Задача была просто вывести, без округлений. И для чего ты добавил `+1`?

2020-03-23 15:54 UTC, smartianin commented on SmartiansJS/main.js
> +console.log(myFood +"\n"+ numOfRollSlices);
Хорошо!

2020-03-24 08:22 UTC, TimonHC commented on SmartiansJS/main.js
> +console.log(Math.floor(Math.random() * (200 + 1)));
math.random() генерирует значения [0;200) 
а так можно получить и 0 и 200

2020-03-24 09:53 UTC, merged