Checkout branch
TimonHC/SmartiansJS pull request #2
Opened 2020-03-25 09:11 UTC by TimonHC

2020-03-25 19:57 UTC, smartianin requested changes
Общее замечание: не разрывай текст задания, а то мне сложно читать его по частям. Пользуйся пробелами и табуляцией.

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +if (isMorning == true){
Возьми себе за привычку, отделять блоки if пустыми линиями

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +}else {console.log("Еще можно спать");}
Поставь пробел

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +if (isMorning == true){
Не используй `==`. Это верный способ наплодить багов. `==` - это оператор нестрогого равенства. Например вот это `0 === '0'` и вот это `0 == '0'` - это разные вещи. `==` сама кастомизирует типы, а `===` проверяет строгое равенство, строго по типу

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +if(currentLevel == 7){
Не скупись на пробелы))

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +if(currentLevel == 7){
```suggestion
if(currentLevel === 7){
```

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +    let driversLicense = true;
Зачем здесь `let`? У блока if своя область видимсоти. И ты по сути создал просто новую переменную

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +{console.log("Waiting for response..")}
```suggestion
let answer = "";

if (answer) console.log("I got a work!");
else console.log("Waiting for response..");
```

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +{console.log("Waiting for response..")}
Правда, так код выглядит читабельнее? ⬆️

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +if (applesInTheBag > 0){
Решил решить задачу навыворот?)) Тогда не нужно проверять на `> 0`, достаточно просто проверить что переменная `applesInTheBag` истинная.  `if (applesInTheBag)`

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +    console.log("isImHungry "+isImHungry);
Обрати внимание на то, что ты повыводил в консоль. Тебе нужно месседжи вывести.

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +let myTool = '';
лишний шаг, можно напрямую

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +myTool += tool|| `pen`;
пробел

2020-03-25 19:57 UTC, smartianin commented on chapter-2.js
> +}else if (today == `Tuesday`){
пробелы и знаки строгого равенства

2020-03-26 07:59 UTC, TimonHC commented on chapter-2.js
> +if (applesInTheBag > 0){
Если передать отрицательное значение, ветвление тоже даст истину, и получится что я сыт, при отрицательном количестве яблок
ну и смотрел бы я в корзину, будучи сытым? :)

2020-03-26 08:52 UTC, merged