Exercises for check
TimonHC/SmartiansJS pull request #5
Opened 2020-04-27 09:53 UTC by TimonHC

2020-04-27 11:02 UTC, smartianin requested changes

2020-04-27 11:02 UTC, smartianin commented on Iterators-chapter-1.js
> +numbers.forEach(numbers =>
```suggestion
numbers.forEach(number =>
```
он как итератор в единственном числе, следи за этим чтобы не запутаться

2020-04-27 11:02 UTC, smartianin commented on Iterators-chapter-1.js
> +const squaredNumbers2 = numbers.map(numbers =>
numbers как массив, и numbers как итератор? Не делай так а то запутаешься. Проверь в остальных случаях

2020-04-27 11:02 UTC, smartianin commented on Iterators-chapter-1.js
> +6. Дан массив с числами. Оставь в нем только отрицательные числа*!/
Суть правильная, только в задании сказано найти отрицательные числа

2020-04-28 15:54 UTC, smartianin requested changes

2020-04-28 15:54 UTC, smartianin commented on Iterators-chapter-2.js
> +const evenNumbers = numbers.filter(number =>
в одну строку

2020-04-28 15:54 UTC, smartianin commented on Iterators-chapter-2.js
> +const longStrings = strings.filter(string =>
тоже самое

2020-04-28 15:54 UTC, smartianin commented on Iterators-chapter-2.js
> +    array.length > 1);
А если это строка? Подумай как переписать

2020-04-29 10:06 UTC, smartianin approved these changes

2020-04-30 08:28 UTC, smartianin commented on Iterators-chapter-3.js
> +    current === 0 ? sumOfNumsBeforeTHeZero = sum : sum;
Поясни эту строчку. Если равно нулю, то присваиваешь значение sum, иначе что?

2020-04-30 08:28 UTC, smartianin commented on Iterators-chapter-3.js
> +    current === 0 ? sumOfNumsBeforeTHeZero = sum : sum;
тоже самое тут. Просто распиши свои мысли

2020-04-30 08:28 UTC, smartianin commented on Iterators-chapter-3.js
> +    (sum > 10) ? countOfElements = index : sum;
да и тут впринципе))

2020-04-30 08:53 UTC, TimonHC commented on Iterators-chapter-3.js
> +    current === 0 ? sumOfNumsBeforeTHeZero = sum : sum;
иначе ничего
пожалуй логичнее будет переделать в If

2020-04-30 09:16 UTC, smartianin reviewed
Выровняй нормально код. Соблюдай пробелы и скобки

2020-05-04 10:21 UTC, smartianin commented on Iterators-chapter-4.js
> +15. Дан массив с числами. Узнай сколько элементов с конца массива надо сложить, чтобы в сумме получилось больше 10-ти.
Читай внимательно задание. И убедись что твой код работает с любыми значениями массива

2020-05-06 08:31 UTC, smartianin approved these changes

2020-05-06 08:32 UTC, merged